### ISSUE TITLE
Hide fiat balance if none of the user's preferred fiat currencies exchange value exceed the minimum amount

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#137]
1. Select multiple fiat currencies
2. Tap on the denomination on the balance screen
3.  If the amount shows - <0.01 it gets stuck and can't switch any further

![image](https://github.com/user-attachments/assets/8b573f80-891f-4d21-93b2-170580895b4f)

**Comment by erdemyerebasmaz** [comment]
If the exchange value of a fiat currency falls below minimum amount, it's considered invalid and skipped when user attempts to change their displayed fiat currency.

This behavior was intended. 

What was not intended is displaying fiat balance when the exchange value is below minimum amount :)

Changing title to reflect the issue.
