### ISSUE TITLE
Bug for removing a pin

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#138]
1. Create a PIN
2. Close the app
3. Open Security & Backup
4. Click deactivate PIN
5. Enter the correct PIN

Shows an error message for half a second but it does not accept it.

https://github.com/user-attachments/assets/895a29d1-bc63-4596-9969-cdc88a3feca1

**Comment by Nackoo2000** [comment]
When removing the PIN if I enter the wrong one the message should stay on the screen so I know what happened.

Additionally, when creating the PIN you can see that I entered the PIN 3 times the 3rd is not right.

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 Can you reproduce this with new builds? Please share logs if you do.

This could be an issue specific to your Android OS version.

I have not been able to reproduce the issue on Android & iOS with latest builds.

**Comment by Nackoo2000** [comment]
Now there is no problem it works as it should.
