### ISSUE TITLE
Balance and history flashing wrong values

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#157]
on iOS created a new node.
The history and balance are flashing with something strange ( first video). When I received a deposit in the node then it continued to flash the history or history and balance (second video).
[l-breez.logs (6).zip](https://github.com/user-attachments/files/16782766/l-breez.logs.6.zip)

https://github.com/user-attachments/assets/3141c1e9-78fc-46b4-9c35-f35fe95340bf

https://github.com/user-attachments/assets/d5b0c805-5fa7-4510-a952-b7de680d7145

**Comment by Nackoo2000** [comment]
This was fixed in the previous versions but reappeared again:

[l-breez.logs (9).zip](https://github.com/user-attachments/files/17017366/l-breez.logs.9.zip)

**Comment by Nackoo2000** [comment]
This happened again in the 6150.1 TestFlight version with one difference.

Previously it flashed the wrong balance and history at any point.
Now it showed the wrong balance and history only before I made the first transaction for a new node.
 Then It kept the correct balance and the history.
[l-breez.logs (15).zip](https://github.com/user-attachments/files/17294309/l-breez.logs.15.zip)

**Comment by erdemyerebasmaz** [comment]
@Nackoo2000 can you reproduce with 6193.1 on TestFlight?
