### ISSUE TITLE
Bad UX for Liquid to Liquid payment

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#161]
When I pay Misty to Misty I do not see that the payment is pending while I am waiting to be complete.

https://github.com/user-attachments/assets/ab740921-0d86-4d40-b49e-0e1ca26efd07

**Comment by roeierez** [comment]
@Nackoo2000 can you check if the pending payment is in the bottom of the list? I have a feeling there is a sorting issue there. cc @erdemyerebasmaz

**Comment by Nackoo2000** [comment]
Yes it does appear on the bottom but there is still time before it does - about 20 to 30 seconds

**Comment by erdemyerebasmaz** [comment]
Depends on
- https://github.com/breez/breez-sdk-liquid/issues/540
