### ISSUE TITLE
Wrong description for receiving payment

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#173]
Description "Send" for a receiving payment. 
![image](https://github.com/user-attachments/assets/55b51cbf-702f-4a23-97cf-5420e4643bd6)

**Comment by erdemyerebasmaz** [comment]
This is the default invoice description from Boltz service. We plan to address this by re-enabling user profiles and use "Payment to <your-username>" as title for these payments as part of #165 

Closing.
