### ISSUE TITLE
Bad UI for liquid failing payment

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#175]
The flush bar text should be better. 

Not sure if there isn't an UX experience that can be better
Proposal: the user is not allowed to make the payment just like the minimum of 1000 sats

https://github.com/user-attachments/assets/45c1b143-0f37-437f-98cf-339bbaf2d35c

**Comment by erdemyerebasmaz** [comment]
We do dismiss payments below minimum payment limits & for those within limits but where the user does not have enough balance we hide "Approve" button and display an "Insufficient local balance" error message on the payment dialog.

I will change the error message on flushbar to "Insufficient local balance" but there appears to be an issue with the SDK as the user has enough local balance to pay the invoice.

CC: @ok300

**Comment by ok300** [comment]
> I will change the error message on flushbar to "Insufficient local balance" but there appears to be an issue with the SDK, possibly with fee calculation, as the user has enough local balance to pay the invoice.

From what I see here, the `InsufficientFunds` error is justified and there's no issue with the SDK:
- scanned invoice is for 2500 sats
- sender (SDK) has 2533 sats available
- sender has to be able to cover the fees
  - as per our docs [^1], the fees are:
    - `~26 sat + ~14 sat + 0.1% service fee` = `~40 sat + 0.1% service fee`
    - these fees are more than the available 33 sats (2533 sat available balance - 2500 sat invoice amount)
    - therefore, the SDK throws `InsufficientFunds`



[^1]: https://sdk-doc-liquid.breez.technology/guide/end-user_fees.html#sending-lightning-payments

**Comment by Nackoo2000** [comment]
1. When I make a Liquid to Liquid payment the fees are ~250 sats - for lighting to liquid or reverse I never had a fee less than 42 sats

2. This case is about how we handle the insufficient funds case - I am intentionally not leaving enough for the fees

**Comment by erdemyerebasmaz** [comment]
Opened an umbrella issue:
 - https://github.com/breez/misty-breez/issues/181
 
to better reflect fees & `prepareSendPayment` errors, which will be handled as part of send payment UI rework #179 .

Closing this by displaying a user friendly error message for now. #178
