### ISSUE TITLE
Receiving offline payment gets "stuck" in pending

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#177]
1. Create an invoice in Misty Breez
2. Scan with Breez Mobile
3. Force close Misty Breez
4. Approve the payment on Breez Mobile
--------------------------------------
5. The payment starts to execute but it is stuck pending in Breez mobile until I open Misty again
6. When I open Misty the payment shows as sent in Breez mobile then becomes pending on Misty and is completed in about a minute.

**Comment by erdemyerebasmaz** [comment]
Force closing an app behaves differently from manufacturer to manufacturer. It can prevent allocating resources to the application to run in background to process the payment. Do you experience the same issue when application is in the background?

**Comment by Nackoo2000** [comment]
Same behavior when in the background

**Comment by erdemyerebasmaz** [comment]
Please share logs to help us investigate the notification plugin.

**Comment by Nackoo2000** [comment]
Receiver logs Misty:
[l-breez.logs (8).zip](https://github.com/user-attachments/files/16963113/l-breez.logs.8.zip)

Sender logs Breez mobile:
[breez.logs (38).zip](https://github.com/user-attachments/files/16963117/breez.logs.38.zip)

**Comment by erdemyerebasmaz** [comment]
Fixed with 
- #190
