### ISSUE TITLE
Improve the UX when payment was successfully received

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#188]
When I receive the payment the screen stays on the QR page it does NOT go back to the balance (home).

I don't know if the bubbles are enough. In BreezM it pops a dialog that says the payment was received but here we are avoiding dialogs so @kingonly should have input on it.

https://github.com/user-attachments/assets/807d3193-b0cf-456d-985b-6f92ad119fb8

**Comment by kingonly** [comment]
No, the bubbles aren't enough. We need to display "Payment Received!" with some kind of success animation in addition to the bubbles, then pop the screen and show the payment entering the list animation that we have now (w/o the bubbles).
