### ISSUE TITLE
Text for insufficiant funds is not displayed propperly

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#217]
When I try to send a transaction that does not cover the fees the text is wrong.

When I try to send a transaction that is bigger than the balance it is OK.
![image](https://github.com/user-attachments/assets/602879fb-1656-432e-9c2c-a77deec3b073)

**Comment by Nackoo2000** [comment]
This is the case when entering an amount that does not cover the fee for sending to LNURL
![image](https://github.com/user-attachments/assets/f04c146b-3467-42a7-a122-d94417a5dd38)

**Comment by erdemyerebasmaz** [comment]
> This is the case when entering an amount that does not cover the fee for sending to LNURL. It does not display any error ![image](https://private-user-images.githubusercontent.com/127208515/381486710-f04c146b-3467-42a7-a122-d94417a5dd38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjQ1MzksIm5iZiI6MTczMDM2NDIzOSwicGF0aCI6Ii8xMjcyMDg1MTUvMzgxNDg2NzEwLWYwNGMxNDZiLTM0NjctNDJhNy1hMTIyLWQ5NDQxN2E1ZGQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwODQzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGU5MjVmZjAxY2I4NTJiZWEwNDMwZTRjMzI2ZGRjNzRhNjE0OTA0Njc1YjRmNmI4MTcxYjhkYTU5N2NhOWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y6a4RY9aENFZeJxjz2p8sDwzpeTeSPnp5yidoZM18yI)

@Nackoo2000 Do you remember how you've input the amount?
Copy + Pasted, manually entered via keyboard, used currency converter dialog etc.

**Comment by Nackoo2000** [comment]
Entered manually in sats
