### ISSUE TITLE
Incorrect Message Displayed When Sending Sats

### ISSUE THREAD

**Issue by Nackoo2000** [breez/misty-breez#219]
The message says "received sats" when I am sending.
![image](https://github.com/user-attachments/assets/01d0ec2c-c54e-4c35-9618-9edc85bc1615)

**Comment by erdemyerebasmaz** [comment]
This is the message from LN Service/Receiver upon receiving the payment successfully. It uses the `successAction` protocol. Protocol specification can be found here: [LUD-09](https://github.com/lnurl/luds/blob/luds/09.md)
