### ISSUE TITLE
App fails to restore on version update

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/misty-breez#85]

**Comment by erdemyerebasmaz** [comment]
This issue is most likely happening due to DB schema changes, as it was not encountered on updating between versions that didn't had any DB changes.

We'll need to mirror & add DB migrations on app layer.

**Comment by roeierez** [comment]
Can you elaborate? which migration changes?  Migrations are handled internally in the sdk and if migration fails it will panic so I don't see how it is related to the fact we see let's breez on upgrade.

**Comment by roeierez** [comment]
I will test again on next package.
